import type { NextPage } from "next";
import Head from "next/head";
import {
  FeaturedProducts,
  GamingProducts,
  HeroBanner,
  Trending,
  UpcomingProducts,
} from "../components";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroBanner />
        <Trending />
        <FeaturedProducts />
        <GamingProducts />
        <UpcomingProducts />
      </main>
    </div>
  );
};

export default Home;
